### PR TITLE
r/bridge_doamin,routing_instance,switch_options,vlan: add `remote-vtep-list` arguments

### LINKED ISSUE #672: Feature request: add "remote-vtep-list" option in "vxlan" block for  resource junos_bridge_domain
### Description

Hi there,

During configuration static vxlan tunnels with bridge-domain + virtual router I faced that Junos requires to tie remote VTEP addresses to bridge domain configuration. So I'd like to ask about implementation this feature in vxlan block for junos_bridge_domain resource

### New or Affected Resource(s)

junos_bridge_domain

### Example Junos Configuration

```
bridge-domains {
      bd1 {
           vlan-id 5;
            vxlan {
                 vni 5005;
                 ingress-node-replication;
                 static-remote-vtep-list [ 10.1.1.1 10.1.1.2 ];
            }
      }
}
```

### Potential Terraform Configuration

```hcl
```hcl
resource "junos_bridge_domain" "bd1" {
  name               = "bd1"
  routing_interface  = "irb.5"
  routing_instance   = "vswitch-bd1"
  vlan_id            = "5"
  domain_type_bridge = true
  interface          = ["ae0.5"]
  vxlan {
    vni                           = 100005
    decapsulate_accept_inner_vlan = null
    encapsulate_inner_vlan        = null
    ingress_node_replication      = true
    remote-vtep-list = [10.1.1.1, 10.1.1.2]
  }
}
```
```

### References
<!--
Are there any other GitHub issues or pull requests that should be linked here? Junos blog posts or documentation? 
-->
Link to Junos docs:

https://www.juniper.net/documentation/us/en/software/junos/evpn-vxlan/topics/ref/statement/static-remote-vtep-list-edit-vlans-bridge-domains-vxlan.html

### LINKED ISSUE #673: Feature request: add "remote-vtep-list" option for resource junos_routing_instance
### Description

Hi there, 

this feature request is related to #672. 
I found out that configuration "static-remote-vtep-list" option in a vxlan block in a "junos_bridge_domain" resource is also required a "remote-vtep-list" configuration for "junos_routing_instance". It's necessary when the type of routing instance is "virtual-switch"

### New or Affected Resource(s)

junos_routing_instance

### Example Junos Configuration

```txt
routing-instances {
    rt1 {
        vtep-source-interface lo0.0;
        remote-vtep-list [ 10.1.1.1 10.1.1.2 ];
        instance-type virtual-switch;
        bridge-domains {
            bd1 {
                vlan-id 5;
                vxlan {
                    vni 500005;
                    ingress-node-replication;
                    static-remote-vtep-list [ 10.1.1.1 10.1.1.2 ];
                }
            }
```

### Potential Terraform Configuration

```hcl
resource "junos_routing_instance" "rt1" {
  name                  = "rt1"
  type                  = "virtual-switch"
  description           = "vSwitch routing instance for static VXLANs"
  vtep_source_interface = "lo0.0"
  remote_vtep_ist       = [ 10.1.1.1, 10.1.1.2 ]
```

### References

From Junos docs:
"On some platforms, you can use this statement with the static-remote-vtep-list statement to also configure remote VTEPs at the VLAN or bridge domain level. When you use the static-remote-vtep-list option, you must configure the remote-vtep-list statement to specify the remote VTEPs at the global level as follows:

In an L2 routing instance of type virtual-switch at the [edit routing-instances name] hierarchy level.

In the default switch instance at the [edit switch-options] hierarchy level."

Link to Junos docs:
https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/remote-vtep-list-routing-instances.html

### PR DESCRIPTION
**Pull request by jeremmfr**
ENHANCEMENTS:

* **resource/junos_bridge_domain**:  add `static_remote_vtep_list` argument inside `vxlan` block argument (Fix #672)
* **resource/junos_routing_instance**:  add `remote_vtep_list` and `remote_vtep_v6_list` arguments (Fix #673)
* **data-source/junos_routing_instance**: add `remote_vtep_list` and `remote_vtep_v6_list` attributes like resource
* **resource/junos_switch_options**:  add `remote_vtep_list` and `remote_vtep_v6_list` arguments
* **resource/junos_vlan**:  add `static_remote_vtep_list` argument inside `vxlan` block argument

### CODE REVIEW

**Comment by Vokunne** [comment]
@jeremmfr hello,

I faced the strange situation. I see that "remote_vtep_list" option has been added starting release 2.8.0, but I can't see it either in the documentation for this resource or using terraform lint in the VSC. In my code I've got an error like this. Could you tell me what I'm doing wrong?

Screenshot 2024-11-15 at 1 14 21 PM

**Comment by Vokunne** [comment]
@jeremmfr I'd like to share an output from junos cli if I'm trying to remove remote-vtep-list option from bridge-domain:
# show | compare 
[edit routing-instances vswitch-test]
-   remote-vtep-list 1.1.1.1;

commit 
[edit routing-instances vswitch-test bridge-domains bd-test]
  'vxlan'
    One of multicast-group or ovsdb-managed or protocols evpn encapsulation vxlan or remote-vtep-list should be enabled. ingress-node-replication must be configured when remote-vtep-list is configured

So it's not possible to use static_remote_vtep_list configuration in terraform resource until remote_vtep_list is configured in main block of "junos_bridge_domain" resource.

**Comment by jeremmfr** [comment]
Hi @Vokunne :wave:

To add [remote-vtep-list](https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/remote-vtep-list-routing-instances.html) option on `[edit routing-instances name]` level, you must add `remote_vtep_list` argument on `junos_routing_instance` resource :

```hcl
resource "junos_routing_instance" "vswitch-test" {
  ...
  remote_vtep_list = ["1.1.1.1"]
  ...
}
```

To add [static-remote-vtep-list](https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/static-remote-vtep-list-edit-vlans-bridge-domains-vxlan.html) option on `[edit routing-instances name bridge-domains name vxlan]` level, you must add `static_remote_vtep_list` argument in `vxlan` block on `junos_bridge_domain` resource :

```hcl
resource "junos_bridge_domain" "name" {
  ...
  vxlan {
    ...
    static_remote_vtep_list = ["1.1.1.1"]
    ...
  }
  ...
}
```

**Comment by Vokunne** [comment]
@jeremmfr thanks a lot. You're absolutely right, I've completely forgotten about this construction.

**Pull request merged**
